export const breads = [
    {
        breadName: 'Italian White',
        breadImg: './img/chose/white.jpg',
        breadCalories: 195,
        breadFat: 2.5,
        breadCarbohydrate: 35,
        breadProtein: 7,
    },
    {
        breadName: 'Honey Oat',
        breadImg: './img/chose/honeyoat.jpg',
        breadCalories: 210,
        breadFat: 2.3,
        breadCarbohydrate: 38,
        breadProtein: 8,
    },
    {
        breadName: 'Wheat',
        breadImg: './img/chose/wheat.jpg',
        breadCalories: 195,
        breadFat: 2.1,
        breadCarbohydrate: 35,
        breadProtein: 8,
    },
    {
        breadName: 'Parmesan Oregano',
        breadImg: './img/chose/parmesanoregano.jpg',
        breadCalories: 206,
        breadFat: 2.7,
        breadCarbohydrate: 37,
        breadProtein: 8,
    }
]
export const meats = [
    {
        meatName: 'Chicken Sliced',
        meatImg: 'img/menu/chicken sliced.png',
        meatCalories: 50,
        meatFat: 0.6,
        meatCarbohydrate: 1,
        meatProtein: 10,
    },
    {
        meatName: 'Chicken Teriyaki',
        meatImg: 'img/menu/chicken teriyaki.png',
        meatCalories: 112,
        meatFat: 1.6,
        meatCarbohydrate: 7,
        meatProtein: 17,
    },
    {
        meatName: 'Italian Meatballs',
        meatImg: 'img/menu/italian meatballs.png',
        meatCalories: 133,
        meatFat: 6.1,
        meatCarbohydrate: 8,
        meatProtein: 10,
    },
    {
        meatName: 'Tuna',
        meatImg: 'img/menu/tuna.png',
        meatCalories: 257,
        meatFat: 23.5,
        meatCarbohydrate: 0,
        meatProtein: 12,
    },
    {
        meatName: 'Shrimp',
        meatImg: 'img/menu/shrimp.png',
        meatCalories: 22,
        meatFat: 0.1,
        meatCarbohydrate: 0,
        meatProtein: 0,
    },
]
 export const veggies = [
    {
        veggieName: 'Lettuce',
        veggieImg: 'img/chose/lettuce.png',
        veggieCalories: 3,
        veggieFat: 0,
        veggieCarbohydrate: 0.4,
        veggieProtein: 0,
    },
    {
        veggieName: 'Tomato',
        veggieImg: 'img/chose/tomatoes.png',
        veggieCalories: 6,
        veggieFat: 0.1,
        veggieCarbohydrate: 1,
        veggieProtein: 0,
    },
    {
        veggieName: 'Cucumber',
        veggieImg: 'img/chose/cucumbers.png',
        veggieCalories: 2,
        veggieFat: 0,
        veggieCarbohydrate: 1,
        veggieProtein: 0,
    },
    {
        veggieName: 'Onion',
        veggieImg: 'img/chose/onions5.jpg',
        veggieCalories: 3,
        veggieFat: 0,
        veggieCarbohydrate: 1,
        veggieProtein: 0,
    },
    {
        veggieName: 'GreenPepper',
        veggieImg: 'img/chose/greenpeppers.png',
        veggieCalories: 1,
        veggieFat: 0,
        veggieCarbohydrate: 0.3,
        veggieProtein: 0,
    },
    {
        veggieName: 'Pickle',
        veggieImg: 'img/chose/pickles.png',
        veggieCalories: 1,
        veggieFat: 0,
        veggieCarbohydrate: 0.2,
        veggieProtein: 0,
    },
    {
        veggieName: 'Olive',
        veggieImg: 'img/chose/olive.png',
        veggieCalories: 4,
        veggieFat: 0.3,
        veggieCarbohydrate: 0.2,
        veggieProtein: 0,
    },
    {
        veggieName: 'Jalapeno',
        veggieImg: 'img/chose/jalapenos.png',
        veggieCalories: 2,
        veggieFat: 0,
        veggieCarbohydrate: 0.2,
        veggieProtein: 0,
    },
]
export const saucesAndCheese = [
    {
        saucesAndCheeseName: 'American Cheese',
        saucesAndCheeseImg: 'img/chose/americancheese.png',
        saucesAndCheeseCalories: 40,
        saucesAndCheeseFat: 3.5,
        saucesAndCheeseCarbohydrate: 1,
        saucesAndCheeseProtein: 2,
    },
    {
        saucesAndCheeseName: 'Shredded Cheese',
        saucesAndCheeseImg: 'img/chose/shreddedcheese.png',
        saucesAndCheeseCalories: 54,
        saucesAndCheeseFat: 4.2,
        saucesAndCheeseCarbohydrate: 1,
        saucesAndCheeseProtein: 3,
    },
    {
        saucesAndCheeseName: 'Mayonnaise',
        saucesAndCheeseImg: 'img/chose/mayonnaise.png',
        saucesAndCheeseCalories: 100,
        saucesAndCheeseFat: 11,
        saucesAndCheeseCarbohydrate: 0,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Sweet Onion',
        saucesAndCheeseImg: 'img/chose/sweetonion.png',
        saucesAndCheeseCalories: 33,
        saucesAndCheeseFat: 0.1,
        saucesAndCheeseCarbohydrate: 8,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Honey Mustard',
        saucesAndCheeseImg: 'img/chose/honeymustard.png',
        saucesAndCheeseCalories: 21,
        saucesAndCheeseFat: 0.1,
        saucesAndCheeseCarbohydrate: 5,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Chipotle Southwest',
        saucesAndCheeseImg: 'img/chose/chipotlesouthwest.png',
        saucesAndCheeseCalories: 66,
        saucesAndCheeseFat: 6.7,
        saucesAndCheeseCarbohydrate: 1,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Yellow Mustard',
        saucesAndCheeseImg: 'img/chose/yellowmustard.png',
        saucesAndCheeseCalories: 9,
        saucesAndCheeseFat: 0.6,
        saucesAndCheeseCarbohydrate: 1,
        saucesAndCheeseProtein: 1,
    },
    {
        saucesAndCheeseName: 'Thousand Island',
        saucesAndCheeseImg: 'img/chose/thousandisland.png',
        saucesAndCheeseCalories: 62,
        saucesAndCheeseFat: 0,
        saucesAndCheeseCarbohydrate: 4,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Olive Oil',
        saucesAndCheeseImg: 'img/chose/oliveoil.png',
        saucesAndCheeseCalories: 44,
        saucesAndCheeseFat: 4.9,
        saucesAndCheeseCarbohydrate: 0,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'RedWine Vinaigar',
        saucesAndCheeseImg: 'img/chose/redwinevinaigar.png',
        saucesAndCheeseCalories: 0.3,
        saucesAndCheeseFat: 0,
        saucesAndCheeseCarbohydrate: 0.1,
        saucesAndCheeseProtein: 0,
    },
    {
        saucesAndCheeseName: 'Italian Dressing',
        saucesAndCheeseImg: 'img/chose/italian dressing.png',
        saucesAndCheeseCalories: 62,
        saucesAndCheeseFat: 0,
        saucesAndCheeseCarbohydrate: 4,
        saucesAndCheeseProtein: 0,
    },
]